// Generated by CoffeeScript 1.3.3
var IChingExecuteXHR, imagemap_, readingresultjsonurl_;

readingresultjsonurl_ = "/ichingreadingcf01/jquery/readingresultjson";

imagemap_ = {
  sangi: {
    dir: "/ichingreadingcf01/images/iching",
    images: {
      oldyang: "icsangiyangB.png",
      youngyang: "icsangiyangB.png",
      oldyin: "icsangiyinB.png",
      youngyin: "icsangiyinB.png",
      init: "sangiW.png"
    }
  },
  kou: {
    dir: "/ichingreadingcf01/images/iching",
    images: {
      oldyang: "oldyangB.png",
      youngyang: "youngyangB.png",
      oldyin: "oldyinB.png",
      youngyin: "youngyinB.png",
      init: "kousymbolW.png"
    }
  },
  hexagram: {
    dir: "/ichingreadingcf01/images/hexagram",
    images: {
      init: "emptyIching-hexagram.png"
    }
  }
};

IChingExecuteXHR = (function() {

  IChingExecuteXHR.prototype.readingresultjsonurl = null;

  function IChingExecuteXHR(imagemap, readingresultjsonurl) {
    this.imagemap = imagemap;
    this.readingresultjsonurl = readingresultjsonurl;
  }

  IChingExecuteXHR.hideresultpane = function() {
    $("#ichingresultpane").hide();
  };

  IChingExecuteXHR.hideperspectivebase = function() {
    $("#hexagramperspectivetablebase").hide();
  };

  IChingExecuteXHR.showresultpane = function() {
    $("#ichingresultpane").show();
  };

  IChingExecuteXHR.showperspectivebase = function() {
    $("#hexagramperspectivetablebase").show();
  };

  IChingExecuteXHR.prototype.initresultkou = function() {
    var koudir, sangidir, _ref, _ref1, _ref2, _ref3;
    if (this.imagemap) {
      sangidir = (_ref = (_ref1 = this.imagemap.sangi) != null ? _ref1.dir : void 0) != null ? _ref : "";
      sangidir = $.trim(sangidir);
      if (sangidir.length > 0) {
        sangidir = sangidir + "/";
      }
      koudir = (_ref2 = (_ref3 = this.imagemap.kou) != null ? _ref3.dir : void 0) != null ? _ref2 : "";
      koudir = $.trim(koudir);
      if (koudir.length > 0) {
        koudir = koudir + "/";
      }
      $(".kousangiimage").attr("src", sangidir + this.imagemap.sangi.images.init);
      $(".kousymbolimage").attr("src", koudir + this.imagemap.kou.images.init);
    }
    $(".kousymbolname").text("");
    $(".kousymbolname").attr("englishname", "none");
  };

  IChingExecuteXHR.prototype.initresulthexagram = function() {
    var hexagramdir, _ref, _ref1;
    if (this.imagemap) {
      hexagramdir = (_ref = (_ref1 = this.imagemap.hexagram) != null ? _ref1.dir : void 0) != null ? _ref : "";
      hexagramdir = $.trim(hexagramdir);
      if (hexagramdir.length > 0) {
        hexagramdir = hexagramdir + "/";
      }
      $(".hexagramimage").attr("src", hexagramdir + this.imagemap.hexagram.images.init);
    }
    $(".hexagramname").text("");
    $(".hexagramalias").text("");
    $(".hexagramaliasenglish").text("");
  };

  IChingExecuteXHR.prototype.replaceresultkousangiimage = function(data) {
    var i, rs, sangidir, ss, _i, _len, _ref, _ref1, _ref2;
    if (data != null ? data.kousresult : void 0) {
      _ref = data.kousresult;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        rs = _ref[i];
        if (rs.kousangiimage) {
          sangidir = (_ref1 = (_ref2 = this.imagemap.sangi) != null ? _ref2.dir : void 0) != null ? _ref1 : "";
          sangidir = $.trim(sangidir);
          if (sangidir.length > 0) {
            sangidir = sangidir + "/";
          }
          ss = sangidir + rs.kousangiimage;
          $("#kousangiimage" + (i + 1)).attr("src", ss);
        }
      }
    }
  };

  IChingExecuteXHR.prototype.replaceresultkousymbolimage = function(data) {
    var i, koudir, rs, ss, _i, _len, _ref, _ref1, _ref2;
    if (data != null ? data.kousresult : void 0) {
      _ref = data.kousresult;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        rs = _ref[i];
        if (rs.kousymbolimage) {
          koudir = (_ref1 = (_ref2 = this.imagemap.kou) != null ? _ref2.dir : void 0) != null ? _ref1 : "";
          koudir = $.trim(koudir);
          if (koudir.length > 0) {
            koudir = koudir + "/";
          }
          ss = koudir + rs.kousymbolimage;
          $("#kousymbolimage" + (i + 1)).attr("src", ss);
        }
      }
    }
  };

  IChingExecuteXHR.prototype.replaceresultkousymbolname = function(data) {
    var i, rs, _i, _len, _ref;
    if (data != null ? data.kousresult : void 0) {
      _ref = data.kousresult;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        rs = _ref[i];
        if (rs.kousymbolname) {
          $("#kousymbolname" + (i + 1)).text(rs.kousymbolname);
        }
        if (rs.kousymbolenglishname) {
          $("#kousymbolname" + (i + 1)).attr("englishname", rs.kousymbolenglishname);
        }
      }
    }
  };

  IChingExecuteXHR.prototype.replaceresulthexagrammain = function(data) {
    var hexagramdir, hn, ss, _ref, _ref1;
    if (data != null ? data.mainresult : void 0) {
      if (data.mainresult.hexagramimage) {
        hexagramdir = (_ref = (_ref1 = this.imagemap.hexagram) != null ? _ref1.dir : void 0) != null ? _ref : "";
        hexagramdir = $.trim(hexagramdir);
        if (hexagramdir.length > 0) {
          hexagramdir = hexagramdir + "/";
        }
        ss = hexagramdir + data.mainresult.hexagramimage;
        $("#hexagramimagemain").attr("src", ss);
      }
      if (data.mainresult.hexagramnumber && data.mainresult.hexagramname) {
        hn = data.mainresult.hexagramnumber + ". " + data.mainresult.hexagramname;
        $("#hexagramnamemain").text(hn);
      }
      if (data.mainresult.hexagramaliasname) {
        $("#hexagramaliasmain").text(data.mainresult.hexagramaliasname);
      }
      if (data.mainresult.hexagramaliasenglishname) {
        $("#hexagramaliasenglishmain").text(data.mainresult.hexagramaliasenglishname);
      }
    }
  };

  IChingExecuteXHR.prototype.replaceresulthexagramperspective = function(data) {
    var hexagramdir, hn, ss, _ref, _ref1;
    if (data != null ? data.perspectiveresult : void 0) {
      IChingExecuteXHR.showperspectivebase();
      if (data.perspectiveresult.hexagramimage) {
        hexagramdir = (_ref = (_ref1 = this.imagemap.hexagram) != null ? _ref1.dir : void 0) != null ? _ref : "";
        hexagramdir = $.trim(hexagramdir);
        if (hexagramdir.length > 0) {
          hexagramdir = hexagramdir + "/";
        }
        ss = hexagramdir + data.perspectiveresult.hexagramimage;
        $("#hexagramimageperspective").attr("src", ss);
      }
      if (data.perspectiveresult.hexagramnumber && data.perspectiveresult.hexagramname) {
        hn = data.perspectiveresult.hexagramnumber + ". " + data.perspectiveresult.hexagramname;
        $("#hexagramnameperspective").text(hn);
      }
      if (data.perspectiveresult.hexagramaliasname) {
        $("#hexagramaliasperspective").text(data.perspectiveresult.hexagramaliasname);
      }
      if (data.perspectiveresult.hexagramaliasenglishname) {
        $("#hexagramaliasenglishperspective").text(data.perspectiveresult.hexagramaliasenglishname);
      }
    }
  };

  IChingExecuteXHR.prototype.bindevent = function() {
    var _this = this;
    $("#readingbtn").button({
      label: 'Reading',
      disabled: false
    }).click(function() {
      $("#readingbtn").button('disable');
      $("#retrybtn").button('disable');
      _this.initresultkou();
      _this.initresulthexagram();
      IChingExecuteXHR.hideperspectivebase();
      IChingExecuteXHR.hideresultpane();
      if (_this.readingresultjsonurl) {
        $.ajax({
          type: "POST",
          async: false,
          url: _this.readingresultjsonurl,
          dataType: "json",
          global: false,
          success: function(data, dataType) {
            IChingExecuteXHR.showresultpane();
            _this.replaceresultkousangiimage(data);
            _this.replaceresultkousymbolimage(data);
            _this.replaceresultkousymbolname(data);
            _this.replaceresulthexagrammain(data);
            _this.replaceresulthexagramperspective(data);
            $("#retrybtn").button('enable');
          },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
            console.error(textStatus);
          }
        });
      }
    });
    $("#retrybtn").button({
      label: 'Retry',
      disabled: true
    }).click(function() {
      $("#readingbtn").button('disable');
      $("#retrybtn").button('disable');
      IChingExecuteXHR.hideperspectivebase();
      IChingExecuteXHR.hideresultpane();
      _this.initresultkou();
      _this.initresulthexagram();
      $("#readingbtn").button('enable');
    });
  };

  return IChingExecuteXHR;

})();

$(document).ready(function() {
  var ichingexecute;
  ichingexecute = new IChingExecuteXHR(imagemap_, readingresultjsonurl_);
  ichingexecute.bindevent();
  IChingExecuteXHR.hideperspectivebase();
  IChingExecuteXHR.hideresultpane();
});
